name: Web E2E Tests

on:
  workflow_dispatch:

jobs:
  e2e-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check Node version
        run: node --version

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: reports
          path: |
            cypress/reports
            cypress/screenshots
            cypress/videos